name: CICD

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - staging
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

permissions:
  id-token: write
  contents: read

jobs:
  cd:
    name: 'Azure Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checking Branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "sqai_repo=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            echo "sqai_repo=staging" >> $GITHUB_OUTPUT
          else
            echo "sqai_repo=dev" >> $GITHUB_OUTPUT
          fi

#      - name: Login to ACR
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
#          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
#          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

#      - name: Build and Push to ACR
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ steps.branch_check.outputs.sqai_repo }}/${{ github.event.repository.name }}:${{ github.sha }}
#          file: Dockerfile

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          yamlConfigPath: .azure/deploy.yml
          targetPort: 8080
          ingress: external
          disableTelemetry: true
          imageToDeploy: squai.azurecr.io/production/test-service:97065687ed38f2b0840a3468143a885b27c6be14
#          acrName: ${{ secrets.AZURE_REGISTRY_USERNAME}}
#          acrUsername: ${{ secrets.AZURE_REGISTRY_USERNAME}}
#          acrPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD}}

#      - name: Build and deploy Container App
#        uses: azure/container-apps-deploy-action@v1
#        with:
#          dockerfilePath: ${{ github.workspace }}/Dockerfile
#          appSourcePath: ${{ github.workspace }}
#          acrName: ${{ secrets.AZURE_REGISTRY_USERNAME}}
#          acrUsername: ${{ secrets.AZURE_REGISTRY_USERNAME}}
#          acrPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD}}
#          containerAppName: ${{ github.event.repository.name }}${{ steps.branch_check.outputs.sqai_repo }}
#          resourceGroup: ${{ secrets.AZURE_SQUARCLE_RESOURCE_GROUP }}
