name: CICD

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - staging
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
  AZURE_ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_ENVIRONMENT: ${{ secrets.AZURE_ENVIRONMENT }}
  AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}

permissions:
  id-token: write
  contents: read

jobs:
  cd:
    name: 'Azure Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checking Branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "sqai_repo=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            echo "sqai_repo=staging" >> $GITHUB_OUTPUT
          else
            echo "sqai_repo=dev" >> $GITHUB_OUTPUT
          fi

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_NAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Set ACR Tag
        run: echo "ACR_TAG=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/${{ steps.branch_check.outputs.sqai_repo }}/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        id: acr
        with:
          push: true
          tags: ${{ env.ACR_TAG }}
          file: Dockerfile

      - name: Use ACR Tag
        run: | 
          echo "Using ACR tag: ${{ env.ACR_TAG }}"
