name: CICD

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - staging
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

#3
jobs:
  linting:
    name: 'Linting'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v3'

      - name: 'Lint code'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
  #         npm run lint
  #  testing:
  #    name: 'Automated Tests'
  #    runs-on: 'ubuntu-latest'
  #    steps:
  #      - name: 'Checkout Code'
  #        uses: 'actions/checkout@v3'
  #
  #      - name: 'Run unit tests'
  #        env:
  #          MONGO_URL_TEST: ${{ secrets.MONGO_URL_TEST }}
  #        run: |
  #          npm ci
  #          npm run test
  cd:
    needs:
      - linting
    #  - testing
    name: 'GCP Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
